name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: User Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        npm install
        npm run build

    - run: ls -la
        
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
